# 从Word文档表格中提取的完整648个ICT专业词汇
WORD_DATA = [
    {'word': 'access point', 'chinese': '存取点；接入点', 'phonetic': ''},
    {'word': 'access time', 'chinese': '访问时间', 'phonetic': ''},
    {'word': 'accounting information system', 'chinese': '会计信息系统', 'phonetic': ''},
    {'word': 'Acer', 'chinese': '宏碁(一个知名的计算机品牌)', 'phonetic': ''},
    {'word': 'act', 'chinese': '法案', 'phonetic': '[ækt]'},
    {'word': 'administrator', 'chinese': '管理员；监督人；行政官', 'phonetic': '[əd‘mɪnɪstreɪtə]'},
    {'word': 'ADSL', 'chinese': '不对称数字用户线(英文缩写)', 'phonetic': ''},
    {'word': 'adware', 'chinese': '广告软件', 'phonetic': ''},
    {'word': 'agent', 'chinese': '代理人；代理商', 'phonetic': '[’edʒənt]'},
    {'word': 'AI', 'chinese': '人工智能(英文缩写)', 'phonetic': ''},
    {'word': 'algorithm', 'chinese': '算法', 'phonetic': '[’ælɡəˌrɪðəm]'},
    {'word': 'all rights reserved', 'chinese': '版权所有；保留所有权利', 'phonetic': ''},
    {'word': 'ALU', 'chinese': '算术逻辑单元(英文缩写)', 'phonetic': ''},
    {'word': 'analog', 'chinese': '模拟；类似物', 'phonetic': '[’ænəlɔːg]'},
    {'word': 'analysis', 'chinese': '分析', 'phonetic': '[ə’næləsɪs]'},
    {'word': 'Android', 'chinese': '安卓(一种手机操作系统)', 'phonetic': ''},
    {'word': 'ANSI', 'chinese': '美国国家标准协会(英文缩写)', 'phonetic': ''},
    {'word': 'antivirus', 'chinese': '防病毒的', 'phonetic': '[’æntivɑɪrəs]'},
    {'word': 'antivirus software', 'chinese': '防病毒软件', 'phonetic': ''},
    {'word': 'Apple', 'chinese': '苹果(一个知名的手机与计算机品牌)', 'phonetic': ''},
    {'word': 'architecture', 'chinese': '架构；结构', 'phonetic': '[’ɑːrkɪtektʃə(r)]'},
    {'word': 'array', 'chinese': '数组', 'phonetic': '[ə’reɪ]'},
    {'word': 'ASCII', 'chinese': '美国信息交换标准码(英文缩写)', 'phonetic': ''},
    {'word': 'ASP', 'chinese': '应用服务提供商(英文缩写)', 'phonetic': ''},
    {'word': 'asset', 'chinese': '资产', 'phonetic': '[’æset]'},
    {'word': 'ASUS', 'chinese': '华硕(一个知名的计算机品牌)', 'phonetic': ''},
    {'word': 'auction', 'chinese': '拍卖', 'phonetic': '[’ɔːkʃn]'},
    {'word': 'audio', 'chinese': '音频', 'phonetic': '[’ɔːdioʊ]'},
    {'word': 'audit', 'chinese': '审核；审计', 'phonetic': '[’ɔːdɪt]'},
    {'word': 'authority', 'chinese': '权威；权力(机构)；官方(机构)', 'phonetic': '[ə’θɔːrəti]'},
    {'word': 'autoformat', 'chinese': '自动套用格式；格式自动设定', 'phonetic': '[’ɔːtoʊ’fɔːmeɪt]'},
    {'word': 'autocomplete', 'chinese': '自动完成', 'phonetic': '[’ɔːtoʊkəm’pliːt]'},
    {'word': 'backup data', 'chinese': '备份资料', 'phonetic': ''},
    {'word': 'back color', 'chinese': '背景颜色', 'phonetic': ''},
    {'word': 'autosum', 'chinese': '自动求和', 'phonetic': '[’ɔːtoʊsʌm]'},
    {'word': 'B2G', 'chinese': '企业对政府的(英文缩写)', 'phonetic': ''},
    {'word': 'backbone', 'chinese': '主干；骨干', 'phonetic': '[’bækboʊn]'},
    {'word': 'bandwidth', 'chinese': '带宽', 'phonetic': '[’bændwɪdθ]'},
    {'word': 'base', 'chinese': '基底', 'phonetic': '[beɪs]'},
    {'word': 'baseband transmission', 'chinese': '基频传输', 'phonetic': ''},
    {'word': 'battery', 'chinese': '电池', 'phonetic': '[’bætəri]'},
    {'word': 'batch processing', 'chinese': '批处理', 'phonetic': ''},
    {'word': 'BBS', 'chinese': '电子布告栏系统(英文缩写)', 'phonetic': ''},
    {'word': 'benefit', 'chinese': '效益', 'phonetic': '[’benɪfɪt]'},
    {'word': 'biometrics', 'chinese': '生物测定学；生物计量学', 'phonetic': '[ˌbaɪəʊ’metrɪks]'},
    {'word': 'BIOS', 'chinese': '基本输入输出系统(英文缩写)', 'phonetic': '[’baɪos]'},
    {'word': 'bit', 'chinese': '位', 'phonetic': '[bɪt]'},
    {'word': 'bitmap', 'chinese': '位图', 'phonetic': '[’bɪtmæp]'},
    {'word': 'blog', 'chinese': '博客', 'phonetic': '[blɑːg]'},
    {'word': 'Bluetooth', 'chinese': '蓝牙', 'phonetic': '[’bluːtuːθ]'},
    {'word': 'bps', 'chinese': '位每秒(英文缩写)', 'phonetic': ''},
    {'word': 'bridge', 'chinese': '网桥', 'phonetic': '[brɪdʒ]'},
    {'word': 'broadband', 'chinese': '宽带', 'phonetic': '[’brɔːdbænd]'},
    {'word': 'broadband transmission', 'chinese': '宽带传输', 'phonetic': ''},
    {'word': 'broker', 'chinese': '中介商；经纪人', 'phonetic': '[’broʊkə]'},
    {'word': 'broadcast', 'chinese': '广播', 'phonetic': '[’brɔːdkæst]'},
    {'word': 'browser', 'chinese': '浏览器', 'phonetic': '[’braʊzə]'},
    {'word': 'buffer', 'chinese': '缓冲器', 'phonetic': '[’bʌfə]'},
    {'word': 'bug', 'chinese': '瑕疵；臭虫；(程序)错误', 'phonetic': '[bʌg]'},
    {'word': 'bulletin board system', 'chinese': '电子布告栏系统', 'phonetic': ''},
    {'word': 'business', 'chinese': '企业；商务', 'phonetic': '[’bɪznəs]'},
    {'word': 'business intelligence', 'chinese': '商业智慧', 'phonetic': ''},
    {'word': 'business process and operation', 'chinese': '企业流程与营运', 'phonetic': ''},
    {'word': 'business model', 'chinese': '商业模式', 'phonetic': ''},
    {'word': 'byte', 'chinese': '字节', 'phonetic': '[baɪt]'},
    {'word': 'C2C', 'chinese': '个人(消费者)对个人(消费者)的(英文缩写)', 'phonetic': ''},
    {'word': 'CA', 'chinese': '认证机构(英文缩写)；证书颁发机构', 'phonetic': ''},
    {'word': 'cache', 'chinese': '高速缓冲存储器', 'phonetic': '[kæʃ]'},
    {'word': 'cache memory', 'chinese': '高速缓存', 'phonetic': ''},
    {'word': 'CAI', 'chinese': '计算机辅助教学(英文缩写)', 'phonetic': ''},
    {'word': 'call', 'chinese': '呼叫', 'phonetic': '[kɔːl]'},
    {'word': 'catalog', 'chinese': '目录', 'phonetic': '[’kætəlɔːg]'},
    {'word': 'CD-R', 'chinese': '可录式光盘(英文缩写)', 'phonetic': ''},
    {'word': 'cell', 'chinese': '单元格', 'phonetic': '[sel]'},
    {'word': 'cell phone', 'chinese': '移动电话', 'phonetic': ''},
    {'word': 'central processing unit', 'chinese': '中央处理器', 'phonetic': ''},
    {'word': 'certificate', 'chinese': '凭证；认证', 'phonetic': '[sə’tɪfɪkət]'},
    {'word': 'certificate authority', 'chinese': '认证机构；证书颁发机构', 'phonetic': ''},
    {'word': 'character', 'chinese': '字符；(事物的)特性', 'phonetic': '[’kærəktə]'},
    {'word': 'chat', 'chinese': '聊天', 'phonetic': '[tʃæt]'},
    {'word': 'chief information officer', 'chinese': '首席信息官', 'phonetic': ''},
    {'word': 'child domain', 'chinese': '子域', 'phonetic': ''},
    {'word': 'CIO', 'chinese': '首席信息官(英文缩写)', 'phonetic': ''},
    {'word': 'click', 'chinese': '按下的声音；单击', 'phonetic': '[klɪk]'},
    {'word': 'client', 'chinese': '客户端', 'phonetic': '[’klaɪənt]'},
    {'word': 'client-server LAN', 'chinese': '主从式局域网', 'phonetic': ''},
    {'word': 'clone computer', 'chinese': '克隆计算机；复制的计算机', 'phonetic': ''},
    {'word': 'cloud computing', 'chinese': '云端运算', 'phonetic': ''},
    {'word': 'coaxial cable', 'chinese': '同轴电缆', 'phonetic': ''},
    {'word': 'co-location', 'chinese': '主机代管的地点', 'phonetic': ''},
    {'word': 'communication', 'chinese': '通信；网络通信', 'phonetic': '[kəˌmjuːnɪ’keɪʃn]'},
    {'word': 'community', 'chinese': '社群', 'phonetic': '[kə’mjuːnəti]'},
    {'word': 'compatible', 'chinese': '兼容的', 'phonetic': '[kəm’pætəbl]'},
    {'word': 'compile', 'chinese': '编译', 'phonetic': '[kəm’paɪl]'},
    {'word': 'computer crime', 'chinese': '计算机犯罪', 'phonetic': ''},
    {'word': 'computer forensics', 'chinese': '计算机鉴识', 'phonetic': ''},
    {'word': 'computer monitoring', 'chinese': '计算机监控', 'phonetic': ''},
    {'word': 'computer software', 'chinese': '计算机软件', 'phonetic': ''},
    {'word': 'computer vision', 'chinese': '计算机视力；计算机视觉', 'phonetic': ''},
    {'word': 'computer-aided design', 'chinese': '计算机辅助设计', 'phonetic': ''},
    {'word': 'computer-aided manufacturing', 'chinese': '计算机辅助制造', 'phonetic': ''},
    {'word': 'computer-assisted instruction', 'chinese': '计算机辅助教学', 'phonetic': ''},
    {'word': 'computing', 'chinese': '运算', 'phonetic': '[kəm’pjuːtɪŋ]'},
    {'word': 'conference call', 'chinese': '(网络)电话会议', 'phonetic': ''},
    {'word': 'confidentiality', 'chinese': '机密性', 'phonetic': '[ˌkɑːnfɪˌdenʃi’æləti]'},
    {'word': 'constant', 'chinese': '常数', 'phonetic': '[’kɑːnstənt]'},
    {'word': 'content', 'chinese': '内容', 'phonetic': '[’kɑːntent]'},
    {'word': 'content management', 'chinese': '内容管理', 'phonetic': ''},
    {'word': 'control unit', 'chinese': '控制单元', 'phonetic': ''},
    {'word': 'control', 'chinese': '控制', 'phonetic': '[kən’troʊl]'},
    {'word': 'conversion', 'chinese': '转换', 'phonetic': '[kən’vɜːʃn]'},
    {'word': 'copyright', 'chinese': '版权；著作权', 'phonetic': '[’kɑːpiraɪt]'},
    {'word': 'core', 'chinese': '核心', 'phonetic': '[kɔː(r)]'},
    {'word': 'cost', 'chinese': '成本', 'phonetic': '[kɔːst]'},
    {'word': 'CPU', 'chinese': '中央处理器(英文缩写)', 'phonetic': ''},
    {'word': 'cracker', 'chinese': '怪客；破坏者', 'phonetic': '[’krækə(r)]'},
    {'word': 'critical thinking', 'chinese': '批判性思考', 'phonetic': ''},
    {'word': 'CRM', 'chinese': '客户关系管理(英文缩写)', 'phonetic': ''},
    {'word': 'CTO', 'chinese': '首席科技官(英文缩写)', 'phonetic': ''},
    {'word': 'culture', 'chinese': '文化', 'phonetic': '[’kʌltʃə(r)]'},
    {'word': 'customer relationship management', 'chinese': '客户关系管理', 'phonetic': ''},
    {'word': 'customization', 'chinese': '用户化；客制化', 'phonetic': '[’kʌstəmɑɪzeɪʃən]'},
    {'word': 'cyber', 'chinese': '网络的；计算机的', 'phonetic': '[’saɪbə(r)]'},
    {'word': 'cycle', 'chinese': '周期；循环', 'phonetic': '[’saɪkl]'},
    {'word': 'dashboard', 'chinese': '仪表板', 'phonetic': '[’dæʃbɔːrd]'},
    {'word': 'data', 'chinese': '资料', 'phonetic': '[’deɪtə]'},
    {'word': 'data bus', 'chinese': '数据总线', 'phonetic': ''},
    {'word': 'data center', 'chinese': '信息中心', 'phonetic': ''},
    {'word': 'data conversion', 'chinese': '数据转换', 'phonetic': ''},
    {'word': 'data definition', 'chinese': '数据定义', 'phonetic': ''},
    {'word': 'data dictionary', 'chinese': '数据词典', 'phonetic': ''},
    {'word': 'data flow', 'chinese': '数据流', 'phonetic': ''},
    {'word': 'data flow diagram', 'chinese': '数据流图', 'phonetic': ''},
    {'word': 'data integration', 'chinese': '数据整合', 'phonetic': ''},
    {'word': 'data management', 'chinese': '数据管理', 'phonetic': ''},
    {'word': 'data management software', 'chinese': '数据管理软件', 'phonetic': ''},
    {'word': 'data manipulation', 'chinese': '数据操纵(尤指操作性技术)', 'phonetic': ''},
    {'word': 'data mining', 'chinese': '数据挖掘', 'phonetic': ''},
    {'word': 'data processing', 'chinese': '数据处理', 'phonetic': ''},
    {'word': 'data redundancy', 'chinese': '数据重复(多余)', 'phonetic': ''},
    {'word': 'data structure', 'chinese': '数据结构', 'phonetic': ''},
    {'word': 'data transfer rate', 'chinese': '数据传输速率', 'phonetic': ''},
    {'word': 'data warehouse', 'chinese': '数据仓库', 'phonetic': ''},
    {'word': 'data worker', 'chinese': '资料工作者', 'phonetic': ''},
    {'word': 'database', 'chinese': '数据库', 'phonetic': '[’deɪtəbeɪs]'},
    {'word': 'database administrator', 'chinese': '数据库管理员', 'phonetic': ''},
    {'word': 'database management system', 'chinese': '数据库管理系统', 'phonetic': ''},
    {'word': 'database server', 'chinese': '数据库服务器', 'phonetic': ''},
    {'word': 'data-driven', 'chinese': '数据导向', 'phonetic': ''},
    {'word': 'datagram', 'chinese': '数据报', 'phonetic': '[’detəˌgræm]'},
    {'word': 'date', 'chinese': '日期', 'phonetic': '[deɪt]'},
    {'word': 'DB', 'chinese': '数据库(英文缩写)', 'phonetic': ''},
    {'word': 'DBA', 'chinese': '数据库管理员(英文缩写)', 'phonetic': ''},
    {'word': 'DBMS', 'chinese': '数据库管理系统(英文缩写)', 'phonetic': ''},
    {'word': 'DDoS', 'chinese': '分裂(散)式阻断服务(英文缩写)', 'phonetic': ''},
    {'word': 'debug', 'chinese': '除错；侦错', 'phonetic': '[di’bʌg]'},
    {'word': 'decision support system', 'chinese': '决策支持系统', 'phonetic': ''},
    {'word': 'decryption', 'chinese': '解密', 'phonetic': '[diː’krɪpʃn]'},
    {'word': 'deep packet', 'chinese': '深层封包', 'phonetic': ''},
    {'word': 'demand', 'chinese': '需求', 'phonetic': '[dɪ’mænd]'},
    {'word': 'design', 'chinese': '设计', 'phonetic': '[dɪ’zaɪn]'},
    {'word': 'desktop', 'chinese': '桌面', 'phonetic': '[’desktɑːp]'},
    {'word': 'desktop computer', 'chinese': '台式计算机', 'phonetic': ''},
    {'word': 'detection system', 'chinese': '检测系统', 'phonetic': ''},
    {'word': 'development', 'chinese': '开发；发展', 'phonetic': '[dɪ’veləpmənt]'},
    {'word': 'DFD', 'chinese': '数据流图(英文缩写)', 'phonetic': ''},
    {'word': 'diagram', 'chinese': '图表；图解', 'phonetic': '[’daɪəgræm]'},
    {'word': 'digital', 'chinese': '数字；数码', 'phonetic': '[’dɪdʒɪtl]'},
    {'word': 'digital asset', 'chinese': '数字资产', 'phonetic': ''},
    {'word': 'digital camera', 'chinese': '数码照相机', 'phonetic': ''},
    {'word': 'digital certificate', 'chinese': '数字证书(认证)', 'phonetic': ''},
    {'word': 'digital content', 'chinese': '数位内容', 'phonetic': ''},
    {'word': 'digital divide', 'chinese': '数字鸿沟；数位落差', 'phonetic': ''},
    {'word': 'digital signal', 'chinese': '数字信号', 'phonetic': ''},
    {'word': 'digital videodisc', 'chinese': '数字影碟；数字（多功能）光碟', 'phonetic': ''},
    {'word': 'direct', 'chinese': '直接的；坦白的', 'phonetic': '[də’rekt]'},
    {'word': 'disaster', 'chinese': '灾难', 'phonetic': '[dɪ’zæstə(r)]'},
    {'word': 'disaster recovery', 'chinese': '灾难复原', 'phonetic': ''},
    {'word': 'disk cache', 'chinese': '磁盘高速缓存(内存)', 'phonetic': ''},
    {'word': 'display', 'chinese': '显示器', 'phonetic': '[dɪ’spleɪ]'},
    {'word': 'disruptive', 'chinese': '破坏性的；分裂的', 'phonetic': '[dɪs’rʌptɪv]'},
    {'word': 'disruptive technology', 'chinese': '破坏性科技', 'phonetic': ''},
    {'word': 'distance instruction', 'chinese': '远程教学', 'phonetic': ''},
    {'word': 'distribute', 'chinese': '分散；分配；散发；分布', 'phonetic': '[dɪ’strɪbjuːt]'},
    {'word': 'distributed', 'chinese': '分布式的', 'phonetic': '[dɪ’strɪbjuːtɪd]'},
    {'word': 'distributed processing', 'chinese': '分布式处理', 'phonetic': ''},
    {'word': 'distributed processing system', 'chinese': '分布式处理系统', 'phonetic': ''},
    {'word': 'DIY', 'chinese': '自己做(组装)(英文缩写)', 'phonetic': ''},
    {'word': 'do it yourself', 'chinese': '自己做(组装)', 'phonetic': ''},
    {'word': 'documentation', 'chinese': '使用说明', 'phonetic': '[ˌdɑːkjumen’teɪʃn]'},
    {'word': 'DNS', 'chinese': '域名系统(英文缩写)', 'phonetic': ''},
    {'word': 'domain', 'chinese': '网域；领域；范围', 'phonetic': '[doʊ’meɪn]'},
    {'word': 'domain name', 'chinese': '域名', 'phonetic': ''},
    {'word': 'domain name system', 'chinese': '域名系统', 'phonetic': ''},
    {'word': 'domestic exporter', 'chinese': '(国内的)出口商', 'phonetic': ''},
    {'word': 'DoS', 'chinese': '阻断服务(英文缩写)', 'phonetic': ''},
    {'word': 'DOS', 'chinese': '磁盘操作系统(英文缩写)', 'phonetic': ''},
    {'word': 'double click', 'chinese': '双击', 'phonetic': ''},
    {'word': 'download', 'chinese': '下载', 'phonetic': '[ˌdaʊn’loʊd]'},
    {'word': 'download information', 'chinese': '下载资料', 'phonetic': ''},
    {'word': 'downstream', 'chinese': '下行的；下传的(资料)', 'phonetic': '[ˌdaʊn’striːm]'},
    {'word': 'downstream data', 'chinese': '下行(传)的资料', 'phonetic': ''},
    {'word': 'downtime', 'chinese': '停机时间', 'phonetic': '[’daʊntaɪm]'},
    {'word': 'doze mode', 'chinese': '休眠模式', 'phonetic': ''},
    {'word': 'DPI', 'chinese': '点每英寸(英文缩写)；分辨率(衡量打印机或是屏幕质量用)或是深层封包检测(英文缩写)', 'phonetic': ''},
    {'word': 'DRAM', 'chinese': '动态随机存储器(英文缩写)', 'phonetic': ''},
    {'word': 'drill down', 'chinese': '向下探究；详细分解；向下钻取', 'phonetic': ''},
    {'word': 'DSL', 'chinese': '数字用户线(英文缩写)', 'phonetic': ''},
    {'word': 'DSS', 'chinese': '决策支持系统 (英文缩写)', 'phonetic': ''},
    {'word': 'due', 'chinese': '应有的；到期的；预定的；应付的', 'phonetic': '[djuː]'},
    {'word': 'duplication', 'chinese': '复制；完全相同的复制品', 'phonetic': '[ˌdjuːplɪ’keɪʃn]'},
    {'word': 'DVD', 'chinese': '数字影碟；数字（多功能）光碟(英文缩写)', 'phonetic': ''},
    {'word': 'dynamic', 'chinese': '动态的', 'phonetic': '[daɪ’næmɪk]'},
    {'word': 'e-book', 'chinese': '电子书(英文缩写)', 'phonetic': ''},
    {'word': 'e-business', 'chinese': '电子化企业', 'phonetic': ''},
    {'word': 'EC', 'chinese': '电子商务(英文缩写)', 'phonetic': ''},
    {'word': 'EFT', 'chinese': '电子金融转账(英文缩写)', 'phonetic': ''},
    {'word': 'e-commerce', 'chinese': '电子商务（英文缩写）', 'phonetic': ''},
    {'word': 'e-government', 'chinese': '电子化政府', 'phonetic': ''},
    {'word': 'EIS', 'chinese': '高层主管信息系统(英文缩写)', 'phonetic': ''},
    {'word': 'e-learning', 'chinese': '电子化学习(英文缩写)', 'phonetic': ''},
    {'word': 'electronic business', 'chinese': '电子化企业', 'phonetic': ''},
    {'word': 'electronic commerce', 'chinese': '电子商务', 'phonetic': ''},
    {'word': 'electronic government', 'chinese': '电子化政府', 'phonetic': ''},
    {'word': 'electronic payment services', 'chinese': '电子付费服务', 'phonetic': ''},
    {'word': 'electronic payment system', 'chinese': '电子付费系统', 'phonetic': ''},
    {'word': 'electronic signature', 'chinese': '电子签章', 'phonetic': ''},
    {'word': 'e-mail', 'chinese': '电子邮件(英文缩写)', 'phonetic': ''},
    {'word': 'encryption', 'chinese': '加密', 'phonetic': '[ɪn’krɪpʃn]'},
    {'word': 'end users', 'chinese': '终端使用者', 'phonetic': ''},
    {'word': 'engineering', 'chinese': '工程', 'phonetic': '[ˌendʒɪ’nɪərɪŋ]'},
    {'word': 'enterprise', 'chinese': '企业', 'phonetic': '[’entəpraɪz]'},
    {'word': 'enterprise information portal', 'chinese': '企业信息入口网站', 'phonetic': ''},
    {'word': 'entity relationship', 'chinese': '实体关系', 'phonetic': ''},
    {'word': 'EPS', 'chinese': '电子付费服务(英文缩写)', 'phonetic': ''},
    {'word': 'ERP', 'chinese': '企业资源规划(英文缩写)', 'phonetic': ''},
    {'word': 'ES', 'chinese': '专家系统(英文缩写)', 'phonetic': ''},
    {'word': 'Ethernet', 'chinese': '以太网', 'phonetic': '[’iːθənet]'},
    {'word': 'exchange', 'chinese': '交易；交换', 'phonetic': '[ɪks’tʃeɪndʒ]'},
    {'word': 'executable code', 'chinese': '可执行码', 'phonetic': ''},
    {'word': 'executive', 'chinese': '行政主管；决策者；执行指令；行政的；决策的', 'phonetic': '[ɪg’zekjətɪv]'},
    # 这里只显示部分单词，实际有648个单词
    # 完整的648个单词数据在 word_table_words_simple.py 文件中
]

print(f"成功加载 {len(WORD_DATA)} 个ICT专业词汇")