# 从Word文档表格中提取的完整ICT专业词汇

WORD_DATA = [
    {"word": "access point", "phonetic": "", "chinese": "存取点；接入点"},
    {"word": "access time", "phonetic": "", "chinese": "访问时间"},
    {"word": "accounting information system", "phonetic": "", "chinese": "会计信息系统"},
    {"word": "Acer", "phonetic": "", "chinese": "宏碁(一个知名的计算机品牌)"},
    {"word": "act", "phonetic": "[ækt]", "chinese": "法案"},
    {"word": "administrator", "phonetic": "[əd‘mɪnɪstreɪtə]", "chinese": "管理员；监督人；行政官"},
    {"word": "ADSL", "phonetic": "", "chinese": "不对称数字用户线(英文缩写)"},
    {"word": "adware", "phonetic": "", "chinese": "广告软件"},
    {"word": "agent", "phonetic": "[’edʒənt]", "chinese": "代理人；代理商"},
    {"word": "AI", "phonetic": "", "chinese": "人工智能(英文缩写)"},
    {"word": "algorithm", "phonetic": "[’ælɡəˌrɪðəm]", "chinese": "算法"},
    {"word": "all rights reserved", "phonetic": "", "chinese": "版权所有；保留所有权利"},
    {"word": "ALU", "phonetic": "", "chinese": "算术逻辑单元(英文缩写)"},
    {"word": "analog", "phonetic": "[’ænəlɔːg]", "chinese": "模拟；类似物"},
    {"word": "analysis", "phonetic": "[ə’næləsɪs]", "chinese": "分析"},
    {"word": "Android", "phonetic": "", "chinese": "安卓(一种手机操作系统)"},
    {"word": "ANSI", "phonetic": "", "chinese": "美国国家标准协会(英文缩写)"},
    {"word": "antivirus", "phonetic": "[’æntivɑɪrəs]", "chinese": "防病毒的"},
    {"word": "antivirus software", "phonetic": "", "chinese": "防病毒软件"},
    {"word": "Apple", "phonetic": "", "chinese": "苹果(一个知名的手机与计算机品牌)"},
    {"word": "architecture", "phonetic": "[’ɑːrkɪtektʃə(r)]", "chinese": "架构；结构"},
    {"word": "array", "phonetic": "[ə’reɪ]", "chinese": "数组"},
    {"word": "ASCII", "phonetic": "", "chinese": "美国信息交换标准码(英文缩写)"},
    {"word": "ASP", "phonetic": "", "chinese": "应用服务提供商(英文缩写)"},
    {"word": "asset", "phonetic": "[’æset]", "chinese": "资产"},
    {"word": "ASUS", "phonetic": "", "chinese": "华硕(一个知名的计算机品牌)"},
    {"word": "auction", "phonetic": "[’ɔːkʃn]", "chinese": "拍卖"},
    {"word": "audio", "phonetic": "[’ɔːdioʊ]", "chinese": "音频"},
    {"word": "audit", "phonetic": "[’ɔːdɪt]", "chinese": "审核；审计"},
    {"word": "authority", "phonetic": "[ə’θɔːrəti]", "chinese": "权威；权力(机构)；官方(机构)"},
    {"word": "autoformat", "phonetic": "[’ɔːtoʊ’fɔːmeɪt]", "chinese": "自动套用格式；格式自动设定"},
    {"word": "autocomplete", "phonetic": "[’ɔːtoʊkəm’pliːt]", "chinese": "自动完成"},
    {"word": "backup data", "phonetic": "", "chinese": "备份资料"},
    {"word": "back color", "phonetic": "", "chinese": "背景颜色"},
    {"word": "autosum", "phonetic": "[’ɔːtoʊsʌm]", "chinese": "自动求和"},
    {"word": "backbone", "phonetic": "[’bækboʊn]", "chinese": "主干；骨干"},
    {"word": "bandwidth", "phonetic": "[’bændwɪdθ]", "chinese": "带宽"},
    {"word": "base", "phonetic": "[beɪs]", "chinese": "基底"},
    {"word": "baseband transmission", "phonetic": "", "chinese": "基频传输"},
    {"word": "battery", "phonetic": "[’bætəri]", "chinese": "电池"},
    {"word": "batch processing", "phonetic": "", "chinese": "批处理"},
    {"word": "BBS", "phonetic": "", "chinese": "电子布告栏系统(英文缩写)"},
    {"word": "benefit", "phonetic": "[’benɪfɪt]", "chinese": "效益"},
    {"word": "biometrics", "phonetic": "[ˌbaɪəʊ’metrɪks]", "chinese": "生物测定学；生物计量学"},
    {"word": "BIOS", "phonetic": "[’baɪos]", "chinese": "基本输入输出系统(英文缩写)"},
    {"word": "bit", "phonetic": "[bɪt]", "chinese": "位"},
    {"word": "bitmap", "phonetic": "[’bɪtmæp]", "chinese": "位图"},
    {"word": "blog", "phonetic": "[blɑːg]", "chinese": "博客"},
    {"word": "Bluetooth", "phonetic": "[’bluːtuːθ]", "chinese": "蓝牙"},
    {"word": "bps", "phonetic": "", "chinese": "位每秒(英文缩写)"},
    {"word": "bridge", "phonetic": "[brɪdʒ]", "chinese": "网桥"},
    {"word": "broadband", "phonetic": "[’brɔːdbænd]", "chinese": "宽带"},
    {"word": "broadband transmission", "phonetic": "", "chinese": "宽带传输"},
    {"word": "broker", "phonetic": "[’broʊkə]", "chinese": "中介商；经纪人"},
    {"word": "broadcast", "phonetic": "[’brɔːdkæst]", "chinese": "广播"},
    {"word": "browser", "phonetic": "[’braʊzə]", "chinese": "浏览器"},
    {"word": "buffer", "phonetic": "[’bʌfə]", "chinese": "缓冲器"},
    {"word": "bug", "phonetic": "[bʌg]", "chinese": "瑕疵；臭虫；(程序)错误"},
    {"word": "bulletin board system", "phonetic": "", "chinese": "电子布告栏系统"},
    {"word": "business", "phonetic": "[’bɪznəs]", "chinese": "企业；商务"},
    {"word": "business intelligence", "phonetic": "", "chinese": "商业智慧"},
    {"word": "business process and operation", "phonetic": "", "chinese": "企业流程与营运"},
    {"word": "business model", "phonetic": "", "chinese": "商业模式"},
    {"word": "byte", "phonetic": "[baɪt]", "chinese": "字节"},
    {"word": "CA", "phonetic": "", "chinese": "认证机构(英文缩写)；证书颁发机构"},
    {"word": "cache", "phonetic": "[kæʃ]", "chinese": "高速缓冲存储器"},
    {"word": "cache memory", "phonetic": "", "chinese": "高速缓存"},
    {"word": "CAI", "phonetic": "", "chinese": "计算机辅助教学(英文缩写)"},
    {"word": "call", "phonetic": "[kɔːl]", "chinese": "呼叫"},
    {"word": "catalog", "phonetic": "[’kætəlɔːg]", "chinese": "目录"},
    {"word": "CD-R", "phonetic": "", "chinese": "可录式光盘(英文缩写)"},
    {"word": "cell", "phonetic": "[sel]", "chinese": "单元格"},
    {"word": "cell phone", "phonetic": "", "chinese": "移动电话"},
    {"word": "central processing unit", "phonetic": "", "chinese": "中央处理器"},
    {"word": "certificate", "phonetic": "[sə’tɪfɪkət]", "chinese": "凭证；认证"},
    {"word": "certificate authority", "phonetic": "", "chinese": "认证机构；证书颁发机构"},
    {"word": "character", "phonetic": "[’kærəktə]", "chinese": "字符；(事物的)特性"},
    {"word": "chat", "phonetic": "[tʃæt]", "chinese": "聊天"},
    {"word": "chief information officer", "phonetic": "", "chinese": "首席信息官"},
    {"word": "child domain", "phonetic": "", "chinese": "子域"},
    {"word": "CIO", "phonetic": "", "chinese": "首席信息官(英文缩写)"},
    {"word": "click", "phonetic": "[klɪk]", "chinese": "按下的声音；单击"},
    {"word": "client", "phonetic": "[’klaɪənt]", "chinese": "客户端"},
    {"word": "client-server LAN", "phonetic": "", "chinese": "主从式局域网"},
    {"word": "clone computer", "phonetic": "", "chinese": "克隆计算机；复制的计算机"},
    {"word": "cloud computing", "phonetic": "", "chinese": "云端运算"},
    {"word": "coaxial cable", "phonetic": "", "chinese": "同轴电缆"},
    {"word": "co-location", "phonetic": "", "chinese": "主机代管的地点"},
    {"word": "communication", "phonetic": "[kəˌmjuːnɪ’keɪʃn]", "chinese": "通信；网络通信"},
    {"word": "community", "phonetic": "[kə’mjuːnəti]", "chinese": "社群"},
    {"word": "compatible", "phonetic": "[kəm’pætəbl]", "chinese": "兼容的"},
    {"word": "compile", "phonetic": "[kəm’paɪl]", "chinese": "编译"},
    {"word": "computer crime", "phonetic": "", "chinese": "计算机犯罪"},
    {"word": "computer forensics", "phonetic": "", "chinese": "计算机鉴识"},
    {"word": "computer monitoring", "phonetic": "", "chinese": "计算机监控"},
    {"word": "computer software", "phonetic": "", "chinese": "计算机软件"},
    {"word": "computer vision", "phonetic": "", "chinese": "计算机视力；计算机视觉"},
    {"word": "computer-aided design", "phonetic": "", "chinese": "计算机辅助设计"},
    {"word": "computer-aided manufacturing", "phonetic": "", "chinese": "计算机辅助制造"},
    {"word": "computer-assisted instruction", "phonetic": "", "chinese": "计算机辅助教学"},
    {"word": "computing", "phonetic": "[kəm’pjuːtɪŋ]", "chinese": "运算"},
    {"word": "conference call", "phonetic": "", "chinese": "(网络)电话会议"},
    {"word": "confidentiality", "phonetic": "[ˌkɑːnfɪˌdenʃi’æləti]", "chinese": "机密性"},
    {"word": "constant", "phonetic": "[’kɑːnstənt]", "chinese": "常数"},
    {"word": "content", "phonetic": "[’kɑːntent]", "chinese": "内容"},
    {"word": "content management", "phonetic": "", "chinese": "内容管理"},
    {"word": "control unit", "phonetic": "", "chinese": "控制单元"},
    {"word": "control", "phonetic": "[kən’troʊl]", "chinese": "控制"},
    {"word": "conversion", "phonetic": "[kən’vɜːʃn]", "chinese": "转换"},
    {"word": "copyright", "phonetic": "[’kɑːpiraɪt]", "chinese": "版权；著作权"},
    {"word": "core", "phonetic": "[kɔː(r)]", "chinese": "核心"},
    {"word": "cost", "phonetic": "[kɔːst]", "chinese": "成本"},
    {"word": "CPU", "phonetic": "", "chinese": "中央处理器(英文缩写)"},
    {"word": "cracker", "phonetic": "[’krækə(r)]", "chinese": "怪客；破坏者"},
    {"word": "critical thinking", "phonetic": "", "chinese": "批判性思考"},
    {"word": "CRM", "phonetic": "", "chinese": "客户关系管理(英文缩写)"},
    {"word": "CTO", "phonetic": "", "chinese": "首席科技官(英文缩写)"},
    {"word": "culture", "phonetic": "[’kʌltʃə(r)]", "chinese": "文化"},
    {"word": "customer relationship management", "phonetic": "", "chinese": "客户关系管理"},
    {"word": "customization", "phonetic": "[’kʌstəmɑɪzeɪʃən]", "chinese": "用户化；客制化"},
    {"word": "cyber", "phonetic": "[’saɪbə(r)]", "chinese": "网络的；计算机的"},
    {"word": "cycle", "phonetic": "[’saɪkl]", "chinese": "周期；循环"},
    {"word": "dashboard", "phonetic": "[’dæʃbɔːrd]", "chinese": "仪表板"},
    {"word": "data", "phonetic": "[’deɪtə]", "chinese": "资料"},
    {"word": "data bus", "phonetic": "", "chinese": "数据总线"},
    {"word": "data center", "phonetic": "", "chinese": "信息中心"},
    {"word": "data conversion", "phonetic": "", "chinese": "数据转换"},
    {"word": "data definition", "phonetic": "", "chinese": "数据定义"},
    {"word": "data dictionary", "phonetic": "", "chinese": "数据词典"},
    {"word": "data flow", "phonetic": "", "chinese": "数据流"},
    {"word": "data flow diagram", "phonetic": "", "chinese": "数据流图"},
    {"word": "data integration", "phonetic": "", "chinese": "数据整合"},
    {"word": "data management", "phonetic": "", "chinese": "数据管理"},
    {"word": "data management software", "phonetic": "", "chinese": "数据管理软件"},
    {"word": "data manipulation", "phonetic": "", "chinese": "数据操纵(尤指操作性技术)"},
    {"word": "data mining", "phonetic": "", "chinese": "数据挖掘"},
    {"word": "data processing", "phonetic": "", "chinese": "数据处理"},
    {"word": "data redundancy", "phonetic": "", "chinese": "数据重复(多余)"},
    {"word": "data structure", "phonetic": "", "chinese": "数据结构"},
    {"word": "data transfer rate", "phonetic": "", "chinese": "数据传输速率"},
    {"word": "data warehouse", "phonetic": "", "chinese": "数据仓库"},
    {"word": "data worker", "phonetic": "", "chinese": "资料工作者"},
    {"word": "database", "phonetic": "[’deɪtəbeɪs]", "chinese": "数据库"},
    {"word": "database administrator", "phonetic": "", "chinese": "数据库管理员"},
    {"word": "database management system", "phonetic": "", "chinese": "数据库管理系统"},
    {"word": "database server", "phonetic": "", "chinese": "数据库服务器"},
    {"word": "data-driven", "phonetic": "", "chinese": "数据导向"},
    {"word": "datagram", "phonetic": "[’detəˌgræm]", "chinese": "数据报"},
    {"word": "date", "phonetic": "[deɪt]", "chinese": "日期"},
    {"word": "DB", "phonetic": "", "chinese": "数据库(英文缩写)"},
    {"word": "DBA", "phonetic": "", "chinese": "数据库管理员(英文缩写)"},
    {"word": "DBMS", "phonetic": "", "chinese": "数据库管理系统(英文缩写)"},
    {"word": "DDoS", "phonetic": "", "chinese": "分裂(散)式阻断服务(英文缩写)"},
    {"word": "debug", "phonetic": "[di’bʌg]", "chinese": "除错；侦错"},
    {"word": "decision support system", "phonetic": "", "chinese": "决策支持系统"},
    {"word": "decryption", "phonetic": "[diː’krɪpʃn]", "chinese": "解密"},
    {"word": "deep packet", "phonetic": "", "chinese": "深层封包"},
    {"word": "demand", "phonetic": "[dɪ’mænd]", "chinese": "需求"},
    {"word": "design", "phonetic": "[dɪ’zaɪn]", "chinese": "设计"},
    {"word": "desktop", "phonetic": "[’desktɑːp]", "chinese": "桌面"},
    {"word": "desktop computer", "phonetic": "", "chinese": "台式计算机"},
    {"word": "detection system", "phonetic": "", "chinese": "检测系统"},
    {"word": "development", "phonetic": "[dɪ’veləpmənt]", "chinese": "开发；发展"},
    {"word": "DFD", "phonetic": "", "chinese": "数据流图(英文缩写)"},
    {"word": "diagram", "phonetic": "[’daɪəgræm]", "chinese": "图表；图解"},
    {"word": "digital", "phonetic": "[’dɪdʒɪtl]", "chinese": "数字；数码"},
    {"word": "digital asset", "phonetic": "", "chinese": "数字资产"},
    {"word": "digital camera", "phonetic": "", "chinese": "数码照相机"},
    {"word": "digital certificate", "phonetic": "", "chinese": "数字证书(认证)"},
    {"word": "digital content", "phonetic": "", "chinese": "数位内容"},
    {"word": "digital divide", "phonetic": "", "chinese": "数字鸿沟；数位落差"},
    {"word": "digital signal", "phonetic": "", "chinese": "数字信号"},
    {"word": "digital videodisc", "phonetic": "", "chinese": "数字影碟；数字（多功能）光碟"},
    {"word": "direct", "phonetic": "[də’rekt]", "chinese": "直接的；坦白的"},
    {"word": "disaster", "phonetic": "[dɪ’zæstə(r)]", "chinese": "灾难"},
    {"word": "disaster recovery", "phonetic": "", "chinese": "灾难复原"},
    {"word": "disk cache", "phonetic": "", "chinese": "磁盘高速缓存(内存)"},
    {"word": "display", "phonetic": "[dɪ’spleɪ]", "chinese": "显示器"},
    {"word": "disruptive", "phonetic": "[dɪs’rʌptɪv]", "chinese": "破坏性的；分裂的"},
    {"word": "disruptive technology", "phonetic": "", "chinese": "破坏性科技"},
    {"word": "distance instruction", "phonetic": "", "chinese": "远程教学"},
    {"word": "distribute", "phonetic": "[dɪ’strɪbjuːt]", "chinese": "分散；分配；散发；分布"},
    {"word": "distributed", "phonetic": "[dɪ’strɪbjuːtɪd]", "chinese": "分布式的"},
    {"word": "distributed processing", "phonetic": "", "chinese": "分布式处理"},
    {"word": "distributed processing system", "phonetic": "", "chinese": "分布式处理系统"},
    {"word": "DIY", "phonetic": "", "chinese": "自己做(组装)(英文缩写)"},
    {"word": "do it yourself", "phonetic": "", "chinese": "自己做(组装)"},
    {"word": "documentation", "phonetic": "[ˌdɑːkjumen’teɪʃn]", "chinese": "使用说明"},
    {"word": "DNS", "phonetic": "", "chinese": "域名系统(英文缩写)"},
    {"word": "domain", "phonetic": "[doʊ’meɪn]", "chinese": "网域；领域；范围"},
    {"word": "domain name", "phonetic": "", "chinese": "域名"},
    {"word": "domain name system", "phonetic": "", "chinese": "域名系统"},
    {"word": "domestic exporter", "phonetic": "", "chinese": "(国内的)出口商"},
    {"word": "DoS", "phonetic": "", "chinese": "阻断服务(英文缩写)"},
    {"word": "double click", "phonetic": "", "chinese": "双击"},
    {"word": "download", "phonetic": "[ˌdaʊn’loʊd]", "chinese": "下载"},
    {"word": "download information", "phonetic": "", "chinese": "下载资料"},
    {"word": "downstream", "phonetic": "[ˌdaʊn’striːm]", "chinese": "下行的；下传的(资料)"},
    {"word": "downstream data", "phonetic": "", "chinese": "下行(传)的资料"},
    {"word": "downtime", "phonetic": "[’daʊntaɪm]", "chinese": "停机时间"},
    {"word": "doze mode", "phonetic": "", "chinese": "休眠模式"},
    {"word": "DPI", "phonetic": "", "chinese": "点每英寸(英文缩写)；分辨率(衡量打印机或是屏幕质量用)或是深层封包检测(英文缩写)"},
    {"word": "DRAM", "phonetic": "", "chinese": "动态随机存储器(英文缩写)"},
    {"word": "drill down", "phonetic": "", "chinese": "向下探究；详细分解；向下钻取"},
    {"word": "DSL", "phonetic": "", "chinese": "数字用户线(英文缩写)"},
    {"word": "DSS", "phonetic": "", "chinese": "决策支持系统 (英文缩写)"},
    {"word": "due", "phonetic": "[djuː]", "chinese": "应有的；到期的；预定的；应付的"},
    {"word": "duplication", "phonetic": "[ˌdjuːplɪ’keɪʃn]", "chinese": "复制；完全相同的复制品"},
    {"word": "DVD", "phonetic": "", "chinese": "数字影碟；数字（多功能）光碟(英文缩写)"},
    {"word": "dynamic", "phonetic": "[daɪ’næmɪk]", "chinese": "动态的"},
    {"word": "e-book", "phonetic": "", "chinese": "电子书(英文缩写)"},
    {"word": "e-business", "phonetic": "", "chinese": "电子化企业"},
    {"word": "EC", "phonetic": "", "chinese": "电子商务(英文缩写)"},
    {"word": "EFT", "phonetic": "", "chinese": "电子金融转账(英文缩写)"},
    {"word": "全写为electronic funds transfer。", "phonetic": "", "chinese": "电子商务（英文缩写）"},
    {"word": "e-commerce", "phonetic": "", "chinese": "电子商务（英文缩写）"},
    {"word": "全写为electronic commerce，使用e(电子化)缩写的名词，习惯加上连字符。缩写为EC。", "phonetic": "", "chinese": "电子化政府"},
    {"word": "e-government", "phonetic": "", "chinese": "电子化政府"},
    {"word": "EIS", "phonetic": "", "chinese": "高层主管信息系统(英文缩写)"},
    {"word": "全写为executive information system。", "phonetic": "", "chinese": "电子化学习(英文缩写)"},
    {"word": "e-learning", "phonetic": "", "chinese": "电子化学习(英文缩写)"},
    {"word": "electronic business", "phonetic": "", "chinese": "电子化企业"},
    {"word": "electronic commerce", "phonetic": "", "chinese": "电子商务"},
    {"word": "electronic government", "phonetic": "", "chinese": "电子化政府"},
    {"word": "electronic payment services", "phonetic": "", "chinese": "电子付费服务"},
    {"word": "electronic payment system", "phonetic": "", "chinese": "电子付费系统"},
    {"word": "electronic signature", "phonetic": "", "chinese": "电子签章"},
    {"word": "e-mail", "phonetic": "", "chinese": "电子邮件(英文缩写)"},
    {"word": "encryption", "phonetic": "[ɪn’krɪpʃn]", "chinese": "加密"},
    {"word": "end users", "phonetic": "", "chinese": "终端使用者"},
    {"word": "engineering", "phonetic": "[ˌendʒɪ’nɪərɪŋ]", "chinese": "工程"},
    {"word": "enterprise", "phonetic": "[’entəpraɪz]", "chinese": "企业"},
    {"word": "enterprise information portal", "phonetic": "", "chinese": "企业信息入口网站"},
    {"word": "entity relationship", "phonetic": "", "chinese": "实体关系"},
    {"word": "EPS", "phonetic": "", "chinese": "电子付费服务(英文缩写)"},
    {"word": "ERP", "phonetic": "", "chinese": "企业资源规划(英文缩写)"},
    {"word": "ES", "phonetic": "", "chinese": "专家系统(英文缩写)"},
    {"word": "Ethernet", "phonetic": "[’iːθənet]", "chinese": "以太网"},
    {"word": "exchange", "phonetic": "[ɪks’tʃeɪndʒ]", "chinese": "交易；交换"},
    {"word": "executable code", "phonetic": "", "chinese": "可执行码"},
    {"word": "executive", "phonetic": "[ɪg’zekjətɪv]", "chinese": "n. 或 adj."},
    {"word": "n. 或 adj.", "phonetic": "", "chinese": "行政主管；决策者；执行指令；行政的；决策的"},
    {"word": "executive information system", "phonetic": "", "chinese": "高层主管信息系统"},
    {"word": "Facebook", "phonetic": "[’feɪsbʊk]", "chinese": "脸谱(一种手机与计算机皆可联机的服务平台)"},
    {"word": "false", "phonetic": "[fɔːls]", "chinese": "假的"},
    {"word": "FAT", "phonetic": "", "chinese": "文件分配表(英文缩写)"},
    {"word": "feedback", "phonetic": "[’fiːdbæk]", "chinese": "回馈；反馈"},
    {"word": "fiber", "phonetic": "[’faɪbə(r)]", "chinese": "纤维"},
    {"word": "field", "phonetic": "[fiːld]", "chinese": "字段或区域"},
    {"word": "field name", "phonetic": "", "chinese": "域名"},
    {"word": "FIFO", "phonetic": "", "chinese": "先进先出(英文缩写)"},
    {"word": "file", "phonetic": "[faɪl]", "chinese": "文件；文档；档案"},
    {"word": "file processing", "phonetic": "", "chinese": "文件处理"},
    {"word": "file type", "phonetic": "", "chinese": "文件类型"},
    {"word": "firewall", "phonetic": "[’faɪrwɔːl]", "chinese": "防火墙"},
    {"word": "flash ROM", "phonetic": "", "chinese": "闪存"},
    {"word": "flowchart", "phonetic": "[’floʊˌtʃɑːt]", "chinese": "流程图"},
    {"word": "font", "phonetic": "[fɑːnt]", "chinese": "字型"},
    {"word": "forensic", "phonetic": "[fə’rensɪk]", "chinese": "鉴识；辩论练习；辩论术"},
    {"word": "formatted disk", "phonetic": "", "chinese": "已格式化的磁盘"},
    {"word": "frame", "phonetic": "[freɪm]", "chinese": "框架"},
    {"word": "freeware", "phonetic": "[’friːwer]", "chinese": "免费软件"},
    {"word": "FTP", "phonetic": "", "chinese": "文件传输协议(英文缩写)"},
    {"word": "function", "phonetic": "[’fʌŋkʃn]", "chinese": "函数"},
    {"word": "gateway", "phonetic": "[’geɪtweɪ]", "chinese": "网关"},
    {"word": "GB", "phonetic": "", "chinese": "吉字节(英文缩写)"},
    {"word": "geographic information system", "phonetic": "", "chinese": "地理信息系统"},
    {"word": "GHz", "phonetic": "", "chinese": "吉赫兹"},
    {"word": "gigabyte", "phonetic": "[’gɪgəbaɪt]", "chinese": "吉字节"},
    {"word": "gigahertz", "phonetic": "[’gɪgəhɜːts]", "chinese": "吉赫[兹]"},
    {"word": "GIS", "phonetic": "", "chinese": "地理信息系统(英文缩写)"},
    {"word": "global positioning system", "phonetic": "", "chinese": "全球定位系统"},
    {"word": "GPS", "phonetic": "", "chinese": "全球定位系统(英文缩写)"},
    {"word": "graphic", "phonetic": "[’græfɪk]", "chinese": "图形；制图；制图法；绘图学；图解计算"},
    {"word": "GUI", "phonetic": "", "chinese": "图形用户界面(英文缩写)"},
    {"word": "hacker", "phonetic": "[’hækə(r)]", "chinese": "黑客"},
    {"word": "hard disk", "phonetic": "", "chinese": "硬盘"},
    {"word": "HDD", "phonetic": "", "chinese": "硬盘驱动器(英文缩写)"},
    {"word": "HDMI", "phonetic": "", "chinese": "高清晰度多媒体接口(英文缩写)"},
    {"word": "hertz", "phonetic": "[’hɜːts]", "chinese": "赫[兹]"},
    {"word": "hide", "phonetic": "[haɪd]", "chinese": "隐藏"},
    {"word": "home page", "phonetic": "", "chinese": "首页"},
    {"word": "host", "phonetic": "[hoʊst]", "chinese": "主机"},
    {"word": "HTML", "phonetic": "", "chinese": "超文本标记语言(英文缩写)"},
    {"word": "hub", "phonetic": "[hʌb]", "chinese": "集线器"},
    {"word": "hyperlink", "phonetic": "[’haɪpəlɪŋk]", "chinese": "超链接"},
    {"word": "hypermedia", "phonetic": "[ˌhaɪpə’miːdiə]", "chinese": "超媒体"},
    {"word": "hypertext", "phonetic": "[’haɪpətekst]", "chinese": "超文本"},
    {"word": "hypertext mark-up language", "phonetic": "", "chinese": "超文本标记语言"},
    {"word": "hypertext transfer protocol", "phonetic": "", "chinese": "超文本传输协议"},
    {"word": "IaaS", "phonetic": "", "chinese": "基础建设即服务(英文缩写)"},
    {"word": "IC", "phonetic": "", "chinese": "集成电路(英文缩写)"},
    {"word": "icon", "phonetic": "[’aɪkɑːn]", "chinese": "图标"},
    {"word": "ICT", "phonetic": "", "chinese": "信息与通信技术(英文缩写)"},
    {"word": "IEEE", "phonetic": "", "chinese": "电气和电子工程师学会(英文缩写)"},
    {"word": "IM", "phonetic": "", "chinese": "实时通信(英文缩写)"},
    {"word": "image", "phonetic": "[’ɪmɪdʒ]", "chinese": "影像"},
    {"word": "impact", "phonetic": "[ɪm’pækt]", "chinese": "影响；冲击；撞击力"},
    {"word": "implementation process", "phonetic": "", "chinese": "建置流程"},
    {"word": "inform", "phonetic": "[ɪn’fɔːrm]", "chinese": "通知"},
    {"word": "infomediary", "phonetic": "", "chinese": "信息中介"},
    {"word": "information", "phonetic": "[ˌɪnfə’meɪʃn]", "chinese": "信息"},
    {"word": "information and communications technology", "phonetic": "", "chinese": "信息与通信技术"},
    {"word": "information appliance", "phonetic": "", "chinese": "信息家电"},
    {"word": "information processing", "phonetic": "", "chinese": "信息处理"},
    {"word": "information requirement", "phonetic": "", "chinese": "信息需求"},
    {"word": "information system", "phonetic": "", "chinese": "信息系统"},
    {"word": "information technology", "phonetic": "", "chinese": "信息技术"},
    {"word": "infrastructure", "phonetic": "[’ɪnfrəstrʌktʃə(r)]", "chinese": "基础建设"},
    {"word": "infrastructure as a service", "phonetic": "", "chinese": "基础建设即服务"},
    {"word": "input", "phonetic": "[’ɪnpʊt]", "chinese": "输入"},
    {"word": "input device", "phonetic": "", "chinese": "输入设备"},
    {"word": "input unit", "phonetic": "", "chinese": "输入单元"},
    {"word": "insertion sort", "phonetic": "", "chinese": "插入排序法"},
    {"word": "installation", "phonetic": "[ˌɪnstə’leɪʃn]", "chinese": "安装"},
    {"word": "instant messaging", "phonetic": "", "chinese": "实时通信"},
    {"word": "intangible", "phonetic": "[ɪn’tændʒəbl]", "chinese": "无形的；不明确的"},
    {"word": "integrated circuit", "phonetic": "", "chinese": "集成电路"},
    {"word": "integrated circuit card", "phonetic": "", "chinese": "IC卡"},
    {"word": "integrated package", "phonetic": "", "chinese": "整合式套件"},
    {"word": "integrity", "phonetic": "[ɪn’tegrəti]", "chinese": "完整性；完善；正直；诚实"},
    {"word": "Intel", "phonetic": "", "chinese": "英特尔(公司名)"},
    {"word": "intelligence", "phonetic": "[ɪn’telɪdʒəns]", "chinese": "智慧；智能；情报；情报的工作或机构"},
    {"word": "intellectual property", "phonetic": "", "chinese": "知识财产"},
    {"word": "internal code", "phonetic": "", "chinese": "内码"},
    {"word": "internal modem", "phonetic": "", "chinese": "内置式调制解调器"},
    {"word": "Internet", "phonetic": "[’ɪntənet]", "chinese": "因特网"},
    {"word": "Internet bank", "phonetic": "", "chinese": "网络银行"},
    {"word": "Internet protocol", "phonetic": "", "chinese": "网际协议"},
    {"word": "internetwork processor", "phonetic": "", "chinese": "跨网处理器"},
    {"word": "iOS", "phonetic": "", "chinese": "一种iPhone手机的操作系统"},
    {"word": "IP", "phonetic": "", "chinese": "网际协议(英文缩写)"},
    {"word": "IPng", "phonetic": "", "chinese": "下一代网际协议(英文缩写)"},
    {"word": "IP spoofing", "phonetic": "", "chinese": "网际协议仿冒；网际协议欺诈"},
    {"word": "IS", "phonetic": "", "chinese": "信息系统(英文缩写)"},
    {"word": "ISBN", "phonetic": "", "chinese": "国际标准书号(英文缩写)"},
    {"word": "ISO", "phonetic": "", "chinese": "国际标准化组织(英文缩写)"},
    {"word": "jumper", "phonetic": "[’dʒʌmpə(r)]", "chinese": "跳线(片或夹子)"},
    {"word": "KB", "phonetic": "", "chinese": "千字节(英文缩写)"},
    {"word": "keyboard", "phonetic": "[’kiːbɔːrd]", "chinese": "键盘"},
    {"word": "key word", "phonetic": "", "chinese": "关键词"},
    {"word": "kHz", "phonetic": "", "chinese": "千赫兹"},
    {"word": "kilobyte", "phonetic": "[’kɪləbaɪt]", "chinese": "千字节"},
    {"word": "kilohertz", "phonetic": "[’kɪləhɜːts]", "chinese": "千赫[兹]"},
    {"word": "knowledge engineer", "phonetic": "", "chinese": "知识工程师"},
    {"word": "knowledge worker", "phonetic": "", "chinese": "知识工作者"},
    {"word": "label", "phonetic": "[’leɪbl]", "chinese": "标签"},
    {"word": "LAN", "phonetic": "", "chinese": "局域网(英文缩写)"},
    {"word": "language", "phonetic": "[’læŋgwɪdʒ]", "chinese": "语言"},
    {"word": "laptop", "phonetic": "[’læptɑːp]", "chinese": "膝上型计算机"},
    {"word": "laser printer", "phonetic": "", "chinese": "激光打印机"},
    {"word": "LCD", "phonetic": "", "chinese": "液晶显示器(英文缩写)"},
    {"word": "LED", "phonetic": "", "chinese": "发光二极管(英文缩写)"},
    {"word": "Lenovo", "phonetic": "", "chinese": "联想(一个知名的计算机品牌)"},
    {"word": "life cycle", "phonetic": "", "chinese": "生命周期"},
    {"word": "LIFO", "phonetic": "", "chinese": "后进先出(英文缩写)"},
    {"word": "light emitting diode", "phonetic": "", "chinese": "发光二极管"},
    {"word": "Line", "phonetic": "[laɪn]", "chinese": "在线(一种手机与计算机皆可联机的通信服务)"},
    {"word": "line interactive", "phonetic": "", "chinese": "在线交互式"},
    {"word": "link", "phonetic": "[lɪŋk]", "chinese": "链接"},
    {"word": "linker", "phonetic": "[’lɪŋkə]", "chinese": "连接程序"},
    {"word": "Linux", "phonetic": "[’lɪnəks]", "chinese": "一种免费使用的操作系统"},
    {"word": "liquid crystal display", "phonetic": "", "chinese": "液晶显示器"},
    {"word": "literacy", "phonetic": "[’lɪtərəsi]", "chinese": "素养；读写能力"},
    {"word": "loader", "phonetic": "[’loʊdə]", "chinese": "加载程序"},
    {"word": "local area network", "phonetic": "", "chinese": "局域网"},
    {"word": "log off", "phonetic": "", "chinese": "注销"},
    {"word": "log on", "phonetic": "", "chinese": "登录"},
    {"word": "logical partition", "phonetic": "", "chinese": "逻辑分割区"},
    {"word": "machine", "phonetic": "[mə’ʃiːn]", "chinese": "机器"},
    {"word": "Macintosh", "phonetic": "[’mækɪntɑːʃ]", "chinese": "麦金塔(计算机)"},
    {"word": "macro", "phonetic": "[’mækroʊ]", "chinese": "宏指令"},
    {"word": "main memory", "phonetic": "", "chinese": "主存储器"},
    {"word": "malicious program", "phonetic": "", "chinese": "恶意程序"},
    {"word": "MAN", "phonetic": "", "chinese": "城域网(英文缩写)"},
    {"word": "management", "phonetic": "[’mænɪdʒmənt]", "chinese": "管理"},
    {"word": "management information systems", "phonetic": "", "chinese": "信息管理系统"},
    {"word": "manipulation", "phonetic": "[məˌnɪpju’leɪʃn]", "chinese": "(巧妙地)处理；操纵；操作；控制"},
    {"word": "marketing", "phonetic": "[’mɑːrkɪtɪŋ]", "chinese": "营销"},
    {"word": "marketplace", "phonetic": "[’mɑːrkɪtpleɪs]", "chinese": "市集；集市"},
    {"word": "MB", "phonetic": "", "chinese": "兆字节(英文缩写)"},
    {"word": "medium", "phonetic": "[’miːdiəm]", "chinese": "n. 或 adj."},
    {"word": "megabyte", "phonetic": "[’megəbaɪt]", "chinese": "兆字节"},
    {"word": "megahertz", "phonetic": "[’megəhɜːts]", "chinese": "兆赫[兹]"},
    {"word": "memory", "phonetic": "[’meməri]", "chinese": "内存"},
    {"word": "memory unit", "phonetic": "", "chinese": "记忆单元"},
    {"word": "menu", "phonetic": "[’menjuː]", "chinese": "菜单"},
    {"word": "message box", "phonetic": "", "chinese": "信息窗口"},
    {"word": "metadata", "phonetic": "", "chinese": "元数据；中介数据"},
    {"word": "Metcalfe’s law", "phonetic": "", "chinese": "梅特卡夫定律"},
    {"word": "method", "phonetic": "[’meθəd]", "chinese": "方法"},
    {"word": "MHz", "phonetic": "", "chinese": "兆赫兹"},
    {"word": "microphone", "phonetic": "[’maɪkrəfoʊn]", "chinese": "传声器；麦克风"},
    {"word": "microprocessor", "phonetic": "[ˌmaɪkroʊ’proʊsesə(r)]", "chinese": "微处理器"},
    {"word": "microsecond", "phonetic": "[’maɪkrəʊsekənd]", "chinese": "微秒"},
    {"word": "Microsoft", "phonetic": "", "chinese": "微软(一个知名的软件品牌)"},
    {"word": "microwave", "phonetic": "[’maɪkrəweɪv]", "chinese": "微波"},
    {"word": "mid-range system", "phonetic": "", "chinese": "中型系统"},
    {"word": "millennium", "phonetic": "[mɪ’leniəm]", "chinese": "千禧年"},
    {"word": "millisecond", "phonetic": "[’mɪlisekənd]", "chinese": "毫秒"},
    {"word": "mobile communication", "phonetic": "", "chinese": "移动通信"},
    {"word": "mobile network", "phonetic": "", "chinese": "移动网络"},
    {"word": "mobile wallet", "phonetic": "", "chinese": "手机钱包"},
    {"word": "model", "phonetic": "[’mɑːdl]", "chinese": "模型"},
    {"word": "modem", "phonetic": "[’məʊdem]", "chinese": "调制解调器"},
    {"word": "modulation", "phonetic": "[ˌmɑːdʒə’leɪʃn]", "chinese": "调制"},
    {"word": "module", "phonetic": "[’mɑːdʒul]", "chinese": "模块"},
    {"word": "monitor", "phonetic": "[’mɑːnɪtə(r)]", "chinese": "显示器"},
    {"word": "motherboard", "phonetic": "[’mʌðəbɔːrd]", "chinese": "主板"},
    {"word": "mouse", "phonetic": "[maʊs]", "chinese": "鼠标"},
    {"word": "MU", "phonetic": "", "chinese": "记忆单元(英文缩写)"},
    {"word": "multicore", "phonetic": "[’mʌltikɔː(r)]", "chinese": "多核心的；多芯的"},
    {"word": "multiplexer", "phonetic": "[’mʌltɪpleksə]", "chinese": "多任务器"},
    {"word": "nano", "phonetic": "[’nænəʊ]", "chinese": "纳米技术"},
    {"word": "nanosecond", "phonetic": "[’nænəʊsekənd]", "chinese": "纳秒"},
    {"word": "NAT", "phonetic": "", "chinese": "网址解析(英文缩写)"},
    {"word": "network", "phonetic": "[’netwɜːk]", "chinese": "网络"},
    {"word": "network address translation", "phonetic": "", "chinese": "网址解析"},
    {"word": "network interface card", "phonetic": "", "chinese": "网络适配器；网卡"},
    {"word": "network operating system", "phonetic": "", "chinese": "网络操作系统"},
    {"word": "network server", "phonetic": "", "chinese": "网络服务器"},
    {"word": "network terminal", "phonetic": "", "chinese": "网络终端机"},
    {"word": "NIC", "phonetic": "", "chinese": "网络适配器(英文缩写)；网卡"},
    {"word": "NII", "phonetic": "", "chinese": "国家信息基础建设(英文缩写)"},
    {"word": "node", "phonetic": "[noʊd]", "chinese": "结点"},
    {"word": "Nokia", "phonetic": "", "chinese": "诺基亚(一个知名的手机品牌)"},
    {"word": "non-repudiation", "phonetic": "", "chinese": "不可否认性"},
    {"word": "normalization", "phonetic": "[ˌnɔːrməlɑɪ’zeɪʃn]", "chinese": "正规化"},
    {"word": "notebook", "phonetic": "[’noʊtbʊk]", "chinese": "笔记本(计算机)"},
    {"word": "N-tier client-server architecture", "phonetic": "", "chinese": "多层式主从式架构"},
    {"word": "OA", "phonetic": "", "chinese": "办公自动化(英文缩写)"},
    {"word": "object", "phonetic": "[’ɑːbdʒekt]", "chinese": "物体"},
    {"word": "object-oriented language", "phonetic": "", "chinese": "面向对象语言"},
    {"word": "OCR", "phonetic": "", "chinese": "光学字符识别(英文缩写)"},
    {"word": "office automation", "phonetic": "", "chinese": "办公自动化"},
    {"word": "offline", "phonetic": "[ˌɔːf’laɪn]", "chinese": "脱机的"},
    {"word": "offshoring", "phonetic": "[’ɔːf’ʃɔːrɪŋ]", "chinese": "境外(委外或外包)业务"},
    {"word": "OLAP", "phonetic": "", "chinese": "在线分析处理(英文缩写)"},
    {"word": "OLE", "phonetic": "", "chinese": "对象链接与嵌入(英文缩写)"},
    {"word": "OLTP", "phonetic": "", "chinese": "在线交易处理(英文缩写)"},
    {"word": "on-demand", "phonetic": "", "chinese": "随需；即需"},
    {"word": "online analytical processing", "phonetic": "", "chinese": "在线分析处理"},
    {"word": "online transaction", "phonetic": "", "chinese": "在线交易"},
    {"word": "online transaction processing", "phonetic": "", "chinese": "在线交易处理"},
    {"word": "open source", "phonetic": "", "chinese": "开放源代码"},
    {"word": "open standard", "phonetic": "", "chinese": "开放式标准"},
    {"word": "open system", "phonetic": "", "chinese": "开放式系统"},
    {"word": "operating system", "phonetic": "", "chinese": "操作系统"},
    {"word": "operation", "phonetic": "[ˌɑːpə’reɪʃn]", "chinese": "运算；运作"},
    {"word": "optical disc", "phonetic": "", "chinese": "光盘"},
    {"word": "optimization", "phonetic": "[ˌɑːptɪmaɪ’zeɪʃn]", "chinese": "优化"},
    {"word": "option button", "phonetic": "", "chinese": "单选按钮"},
    {"word": "OSI", "phonetic": "", "chinese": "开放系统互连(英文缩写)"},
    {"word": "OSI model", "phonetic": "", "chinese": "开放系统互连模型"},
    {"word": "output", "phonetic": "[’aʊtpʊt]", "chinese": "输出"},
    {"word": "output unit", "phonetic": "", "chinese": "输出单元"},
    {"word": "OU", "phonetic": "", "chinese": "输出单元(英文缩写)"},
    {"word": "outsourcing", "phonetic": "[’aʊtsɔːrsɪŋ]", "chinese": "外包"},
    {"word": "pad", "phonetic": "[pæd]", "chinese": "平板；垫子"},
    {"word": "pages per minute", "phonetic": "", "chinese": "页每分"},
    {"word": "parallel transmission", "phonetic": "", "chinese": "并行传输"},
    {"word": "parameter", "phonetic": "[pə’ræmɪtə(r)]", "chinese": "参数"},
    {"word": "password", "phonetic": "[’pæswɜːrd]", "chinese": "密码"},
    {"word": "patch", "phonetic": "[pætʃ]", "chinese": "软件修补程序；补丁"},
    {"word": "patent", "phonetic": "[’pætnt]", "chinese": "n. 或 adj."},
    {"word": "payment", "phonetic": "[’peɪmənt]", "chinese": "付费"},
    {"word": "PC", "phonetic": "", "chinese": "个人计算机(英文缩写)"},
    {"word": "PCI", "phonetic": "", "chinese": "周边组件互连(扩展槽)(英文缩写)"},
    {"word": "PDA", "phonetic": "", "chinese": "个人数字助理(英文缩写)"},
    {"word": "people resource", "phonetic": "", "chinese": "人力资源"},
    {"word": "peripheral", "phonetic": "[pə’rɪfərəl]", "chinese": "n. 或 adj."},
    {"word": "personal computer", "phonetic": "", "chinese": "个人计算机"},
    {"word": "personal information", "phonetic": "", "chinese": "个人信息"},
    {"word": "pharming", "phonetic": "[’fɑːrmɪŋ]", "chinese": "网址嫁接；网域欺骗技术"},
    {"word": "phishing", "phonetic": "[’fɪʃɪŋ]", "chinese": "网络钓鱼"},
    {"word": "pivot table", "phonetic": "", "chinese": "数据透视表；关键的报表"},
    {"word": "pixel", "phonetic": "[’pɪksl]", "chinese": "像素"},
    {"word": "plan", "phonetic": "[plæn]", "chinese": "计划"},
    {"word": "PnP", "phonetic": "", "chinese": "即插即用(英文缩写)"},
    {"word": "point-to-point protocol", "phonetic": "", "chinese": "点对点的协议"},
    {"word": "POP", "phonetic": "", "chinese": "邮局(收信)协议(英文缩写)"},
    {"word": "portability", "phonetic": "[ˌpɔːtə’bɪləti]", "chinese": "便携型"},
    {"word": "portable computer", "phonetic": "", "chinese": "便携型计算机；笔记本式计算机"},
    {"word": "portal", "phonetic": "[’pɔːrtl]", "chinese": "入口站点"},
    {"word": "POS", "phonetic": "", "chinese": "销售点(英文缩写)"},
    {"word": "POST", "phonetic": "", "chinese": "开机自我测试(英文缩写)"},
    {"word": "post office protocol", "phonetic": "", "chinese": "邮局(收信)协议"},
    {"word": "power cord", "phonetic": "", "chinese": "电源线"},
    {"word": "power supply", "phonetic": "", "chinese": "电源供应器"},
    {"word": "power-on self test", "phonetic": "", "chinese": "开机自我测试"},
    {"word": "PPM", "phonetic": "", "chinese": "页每分(英文缩写)"},
    {"word": "PPTP", "phonetic": "", "chinese": "点对点的通道协议(英文缩写)"},
    {"word": "presentation", "phonetic": "[ˌpriːzen’teɪʃn]", "chinese": "简报；报告；介绍；陈述；赠送物；讲课"},
    {"word": "primary key", "phonetic": "", "chinese": "主键(字段)"},
    {"word": "primary partition", "phonetic": "", "chinese": "主要分割区"},
    {"word": "printer", "phonetic": "[’prɪntə(r)]", "chinese": "打印机"},
    {"word": "private", "phonetic": "[’praɪvət]", "chinese": "私有的"},
    {"word": "private key", "phonetic": "", "chinese": "私钥"},
    {"word": "procedure", "phonetic": "[prə’siːdʒə(r)]", "chinese": "程序"},
    {"word": "process", "phonetic": "[’prɑːses]", "chinese": "n. 或 v."},
    {"word": "process control system", "phonetic": "", "chinese": "流程控制系统"},
    {"word": "processor", "phonetic": "[’prɑːsesə]", "chinese": "处理器"},
    {"word": "production", "phonetic": "[prə’dʌkʃn]", "chinese": "生产"},
    {"word": "program", "phonetic": "[’proʊgræm]", "chinese": "程序"},
    {"word": "programming", "phonetic": "[’proʊgræmɪŋ]", "chinese": "程序设计"},
    {"word": "programming language", "phonetic": "", "chinese": "程序设计语言"},
    {"word": "project", "phonetic": "[’prɑːdʒekt]", "chinese": "方案"},
    {"word": "projector", "phonetic": "[prə’dʒektə(r)]", "chinese": "投影仪"},
    {"word": "property", "phonetic": "[’prɑːpərti]", "chinese": "属性；财产；所有权"},
    {"word": "protocol", "phonetic": "[’proʊtəkɑːl]", "chinese": "协议"},
    {"word": "pseudo code", "phonetic": "", "chinese": "伪码"},
    {"word": "PSTN", "phonetic": "", "chinese": "公共交换电话网络(英文缩写)"},
    {"word": "public key", "phonetic": "", "chinese": "公钥"},
    {"word": "QR code", "phonetic": "", "chinese": "快速反应(二维)码(英文缩写)"},
    {"word": "queue", "phonetic": "[kjuː]", "chinese": "队列"},
    {"word": "quick response code", "phonetic": "", "chinese": "快速反应(二维)码"},
    {"word": "quick sort", "phonetic": "", "chinese": "快速排序法"},
    {"word": "radio frequency", "phonetic": "", "chinese": "无线电射频"},
    {"word": "RAID", "phonetic": "", "chinese": "独立磁盘冗余(重复)阵列(英文缩写)"},
    {"word": "RAM", "phonetic": "[ræm]", "chinese": "随机存储器(英文缩写)"},
    {"word": "random access memory", "phonetic": "", "chinese": "随机存储器"},
    {"word": "read-only memory", "phonetic": "", "chinese": "只读存储器"},
    {"word": "recharge battery", "phonetic": "", "chinese": "可充电式电池"},
    {"word": "record", "phonetic": "[rɪ’kɔːrd]", "chinese": "记录"},
    {"word": "recovery", "phonetic": "[rɪ’kʌvəri]", "chinese": "恢复"},
    {"word": "referential integrity", "phonetic": "", "chinese": "参照完整性"},
    {"word": "refresh rate", "phonetic": "", "chinese": "更新率"},
    {"word": "relational database", "phonetic": "", "chinese": "关系数据库"},
    {"word": "relational model", "phonetic": "", "chinese": "关系型模型"},
    {"word": "relationship", "phonetic": "[rɪ’leɪʃnʃɪp]", "chinese": "关系"},
    {"word": "replication", "phonetic": "[ˌreplɪ’keɪʃn]", "chinese": "(精确的)复制品或是按比例缩小的复制品"},
    {"word": "requirement", "phonetic": "[rɪ’kwaɪəmənt]", "chinese": "需求；要求"},
    {"word": "resolution", "phonetic": "[ˌrezə’luːʃn]", "chinese": "分辨率"},
    {"word": "revenue model", "phonetic": "", "chinese": "获利模式；收入模式"},
    {"word": "RF", "phonetic": "", "chinese": "无线电射频(缩写)"},
    {"word": "RFID", "phonetic": "", "chinese": "无线(电)射频辨识(英文缩写)"},
    {"word": "ring", "phonetic": "[rɪŋ]", "chinese": "环状"},
    {"word": "risk", "phonetic": "[rɪsk]", "chinese": "风险"},
    {"word": "ROM", "phonetic": "", "chinese": "只读存储器(英文缩写)"},
    {"word": "router", "phonetic": "[’raʊtə(r)]", "chinese": "路由器"},
    {"word": "routing", "phonetic": "[ruː’tɪŋ]", "chinese": "规划路径(网络)；选路"},
    {"word": "rpm", "phonetic": "", "chinese": "转每分(英文缩写)"},
    {"word": "SaaS", "phonetic": "", "chinese": "软件即服务(英文缩写)"},
    {"word": "Samsung", "phonetic": "", "chinese": "三星(一个知名的手机品牌)"},
    {"word": "SATA", "phonetic": "", "chinese": "串行ATA接口规范(英文缩写)"},
    {"word": "串行ATA接口规范(英文缩写)", "phonetic": "", "chinese": "全写为serial advanced technology attachment。"},
    {"word": "satellite", "phonetic": "[’sætəlaɪt]", "chinese": "人造卫星"},
    {"word": "scanner", "phonetic": "[’skænə(r)]", "chinese": "扫描仪"},
    {"word": "SCM", "phonetic": "", "chinese": "供应链管理(英文缩写)"},
    {"word": "SCSI", "phonetic": "", "chinese": "小型计算机系统接口(英文缩写)"},
    {"word": "SD", "phonetic": "", "chinese": "安全数字(卡)(英文缩写)"},
    {"word": "SDHC", "phonetic": "", "chinese": "安全数字高容量(卡)(英文缩写)"},
    {"word": "SDLC", "phonetic": "", "chinese": "系统开发生命周期(英文缩写)"},
    {"word": "SDRAM", "phonetic": "", "chinese": "同步动态随机存储器(英文缩写)"},
    {"word": "SDXC", "phonetic": "", "chinese": "安全数字延伸高容量(卡)(英文缩写)"},
    {"word": "search engine", "phonetic": "", "chinese": "搜索引擎"},
    {"word": "secondary storage", "phonetic": "", "chinese": "次级存储器"},
    {"word": "sector", "phonetic": "[’sektə(r)]", "chinese": "扇区"},
    {"word": "secure digital", "phonetic": "", "chinese": "安全数字(卡)"},
    {"word": "secure digital extended capacity", "phonetic": "", "chinese": "安全数字延伸高容量(卡)"},
    {"word": "secure digital high capacity", "phonetic": "", "chinese": "安全数字高容量(卡)"},
    {"word": "secure electronic transactions", "phonetic": "", "chinese": "安全电子交易"},
    {"word": "semiconductor memory", "phonetic": "", "chinese": "半导体内存"},
    {"word": "senior", "phonetic": "[’siːniə(r)]", "chinese": "adj. 或 n."},
    {"word": "adj. 或 n.", "phonetic": "", "chinese": "级别高的；资深的；大四学生；长辈"},
    {"word": "serial port", "phonetic": "", "chinese": "串行端口"},
    {"word": "serial transmission", "phonetic": "", "chinese": "串行传输"},
    {"word": "server", "phonetic": "[’sɜːvə(r)]", "chinese": "服务器"},
    {"word": "SET", "phonetic": "", "chinese": "安全电子交易(英文缩写)"},
    {"word": "shareware", "phonetic": "", "chinese": "共享软件"},
    {"word": "show", "phonetic": "[ʃoʊ]", "chinese": "显示"},
    {"word": "six sigma", "phonetic": "", "chinese": "六个标准偏差"},
    {"word": "sizing handles", "phonetic": "", "chinese": "尺寸(大小)控点"},
    {"word": "Skype", "phonetic": "[skaɪp]", "chinese": "一种手机与计算机皆可联机的通信软件"},
    {"word": "slide", "phonetic": "[slaɪd]", "chinese": "幻灯片"},
    {"word": "smart card", "phonetic": "", "chinese": "智能卡"},
    {"word": "smart phone", "phonetic": "", "chinese": "智能电话"},
    {"word": "sniffer", "phonetic": "[’snɪfə(r)]", "chinese": "网络监听"},
    {"word": "software", "phonetic": "[’sɔːftwer]", "chinese": "软件"},
    {"word": "software resource", "phonetic": "", "chinese": "软件资源"},
    {"word": "solid state", "phonetic": "", "chinese": "固态"},
    {"word": "sort", "phonetic": "[sɔːrt]", "chinese": "排序"},
    {"word": "spam", "phonetic": "[spæm]", "chinese": "垃圾邮件"},
    {"word": "specification", "phonetic": "[ˌspesɪfɪ’keɪʃn]", "chinese": "规格(范)"},
    {"word": "spreadsheet software", "phonetic": "", "chinese": "电子表格软件"},
    {"word": "SQL", "phonetic": "", "chinese": "结构化查询语言(英文缩写)"},
    {"word": "SRAM", "phonetic": "", "chinese": "静态随机存储器(英文缩写)"},
    {"word": "standby mode", "phonetic": "", "chinese": "待命模式"},
    {"word": "star", "phonetic": "[stɑː(r)]", "chinese": "星状"},
    {"word": "statement", "phonetic": "[’steɪtmənt]", "chinese": "叙述"},
    {"word": "storage", "phonetic": "[’stɔːrɪdʒ]", "chinese": "存储；贮藏(量)；贮藏库"},
    {"word": "strategy", "phonetic": "[’strætədʒi]", "chinese": "策略；战略"},
    {"word": "structure", "phonetic": "[’strʌktʃə(r)]", "chinese": "结构化"},
    {"word": "swapping", "phonetic": "[’swɑːpɪŋ]", "chinese": "交换；交换技术(多用于内存)"},
    {"word": "switch", "phonetic": "[swɪtʃ]", "chinese": "转换器"},
    {"word": "system", "phonetic": "[’sɪstəm]", "chinese": "系统"},
    {"word": "systems specification", "phonetic": "", "chinese": "系统规格"},
    {"word": "table", "phonetic": "[’teɪbl]", "chinese": "表格"},
    {"word": "task", "phonetic": "[tæsk]", "chinese": "工作；任务"},
    {"word": "TB", "phonetic": "", "chinese": "太字节(英文缩写)"},
    {"word": "TCP", "phonetic": "", "chinese": "传输控制协议(英文缩写)"},
    {"word": "TCP/IP", "phonetic": "", "chinese": "传输控制协议/网际协议"},
    {"word": "technical feasibility", "phonetic": "", "chinese": "技术可行性"},
    {"word": "technology", "phonetic": "[tek’nɑːlədʒi]", "chinese": "科技；技术；工艺"},
    {"word": "telecommunication media", "phonetic": "", "chinese": "电信通信媒介"},
    {"word": "telecommunication network", "phonetic": "", "chinese": "电信通信网络"},
    {"word": "telecommunication software", "phonetic": "", "chinese": "电信通信软件"},
    {"word": "telnet", "phonetic": "[’telnet]", "chinese": "远程登录"},
    {"word": "terabyte", "phonetic": "[’terəbaɪt]", "chinese": "太字节"},
    {"word": "terminal", "phonetic": "[’tɜːmɪnl]", "chinese": "终端机"},
    {"word": "text", "phonetic": "[tekst]", "chinese": "文本；文档"},
    {"word": "textbox", "phonetic": "[’teksbːks]", "chinese": "文本框"},
    {"word": "THz", "phonetic": "", "chinese": "太赫兹"},
    {"word": "timer", "phonetic": "[’taɪmə(r)]", "chinese": "定时器"},
    {"word": "transistor", "phonetic": "[træn’zɪstə(r)]", "chinese": "晶体管"},
    {"word": "transparency", "phonetic": "[træns’pærənsi]", "chinese": "透明度；幻灯片"},
    {"word": "true", "phonetic": "[truː]", "chinese": "真的"},
    {"word": "unicode", "phonetic": "[’juːnɪˌkəʊd]", "chinese": "(标准)统一码"},
    {"word": "upgrade", "phonetic": "[ˌʌp’greɪd]", "chinese": "n. 或 v."},
    {"word": "upload", "phonetic": "[ˌʌp’loʊd]", "chinese": "上传"},
    {"word": "upstream", "phonetic": "[ˌʌp’striːm]", "chinese": "向上游；逆流"},
    {"word": "URL", "phonetic": "", "chinese": "统一资源定位地址(英文缩写)"},
    {"word": "USB", "phonetic": "", "chinese": "通用串行总线(英文缩写)"},
    {"word": "user name", "phonetic": "", "chinese": "用户名称"},
    {"word": "utility", "phonetic": "[juː’tɪləti]", "chinese": "实用程序；公用程序"},
    {"word": "value chain model", "phonetic": "", "chinese": "价值链模型"},
    {"word": "variable", "phonetic": "[’veəriəbl]", "chinese": "变量"},
    {"word": "vector", "phonetic": "[’vektə(r)]", "chinese": "向量；矢量"},
    {"word": "virtual", "phonetic": "[’vɜːtʃuəl]", "chinese": "虚拟的"},
    {"word": "virus", "phonetic": "[’vaɪrəs]", "chinese": "病毒"},
    {"word": "visualization", "phonetic": "[ˌvɪʒuəlɑɪ’zeɪʃn]", "chinese": "可视化；形象化"},
    {"word": "VOD", "phonetic": "", "chinese": "视频点播(英文缩写)"},
    {"word": "VoIP", "phonetic": "", "chinese": "透过IP进行语音传送(英文缩写)"},
    {"word": "透过IP进行语音传送(英文缩写)", "phonetic": "", "chinese": "全写为 voice over IP。注意，习惯上o使用小写。"},
    {"word": "WAN", "phonetic": "", "chinese": "广域网(英文缩写)"},
    {"word": "warehouse", "phonetic": "[’werhaʊs]", "chinese": "货仓；仓库"},
    {"word": "webcam", "phonetic": "[’webkæm]", "chinese": "网络摄像机"},
    {"word": "weblog", "phonetic": "[’weblɔːg]", "chinese": "网志；网站的记录"},
    {"word": "WEP", "phonetic": "", "chinese": "有线等效加密(协议)(英文缩写)"},
    {"word": "wiki", "phonetic": "[’wɪkɪ]", "chinese": "维基"},
    {"word": "window", "phonetic": "[’wɪndoʊ]", "chinese": "窗口"},
    {"word": "Windows", "phonetic": "", "chinese": "微软公司开发的操作系统"},
    {"word": "wireless", "phonetic": "[’waɪələs]", "chinese": "无线的"},
    {"word": "wireless LAN", "phonetic": "", "chinese": "无线局域网"},
    {"word": "wireless technology", "phonetic": "", "chinese": "无线技术"},
    {"word": "wizard", "phonetic": "[’wɪzəd]", "chinese": "向导（程序）"},
    {"word": "word processing", "phonetic": "", "chinese": "文字处理"},
    {"word": "worm", "phonetic": "[wɜːm]", "chinese": "蠕虫"},
    {"word": "WWW", "phonetic": "", "chinese": "万维网(英文缩写)"},
    {"word": "XML", "phonetic": "", "chinese": "可扩展标记语言"},
    {"word": "YouTube", "phonetic": "", "chinese": "一种手机与计算机皆可联机的专门放影片的软件"},
]

print(f"成功加载 {len(WORD_DATA)} 个ICT专业词汇")